import {test,expect} from 'playwright/test';
const state=page=>page.evaluate(()=>window.__profileAdventureDebug.getState());
async function ready(page){await page.goto('/#profile',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__profileAdventureDebug?.getState().ready);await page.locator('.profile-adventure-stage').scrollIntoViewIfNeeded();}
test.beforeEach(async({page})=>{await page.route('https://api.visitorbadge.io/**',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg"/>'}));});
for(const width of [1440,1024,768,390,360])test(`whole cabin preserves 4:3 at ${width}px`,async({page})=>{await page.setViewportSize({width,height:1000});await ready(page);const metrics=await page.locator('.profile-adventure-stage').evaluate(el=>{const r=el.getBoundingClientRect(),c=el.querySelector('canvas');return{ratio:r.width/r.height,render:[c.width,c.height],overflow:document.documentElement.scrollWidth-innerWidth,left:r.left,right:r.right};});expect(metrics.ratio).toBeCloseTo(4/3,2);expect(metrics.render).toEqual([640,480]);expect(metrics.overflow).toBeLessThanOrEqual(1);expect(metrics.left).toBeGreaterThanOrEqual(0);expect(metrics.right).toBeLessThanOrEqual(width+1);await page.locator('.future-slot').screenshot({path:`artifacts/cabin-v6/cabin-${width}.png`});});
test('five characters can be controlled; blur and dialogs clear movement',async({page})=>{
 await ready(page);await page.evaluate(()=>window.__profileAdventureDebug.pause());
 for(const id of ['nobita','doraemon','shizuka','gian','suneo']){await page.locator(`[data-profile-actor=${id}]`).click();expect((await state(page)).controlledActor).toBe(id);await page.keyboard.press('Escape');expect((await state(page)).controlledActor).toBeNull();}
 await page.evaluate(()=>window.__profileAdventureDebug.reset());await page.locator('[data-profile-actor=nobita]').click();const start=(await state(page)).actors.nobita.walkDistance;await page.keyboard.down('d');await page.waitForTimeout(350);await page.keyboard.up('d');expect((await state(page)).actors.nobita.walkDistance).toBeGreaterThan(start);
 await page.keyboard.down('s');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));const stopped=(await state(page)).actors.nobita.walkDistance;await page.waitForTimeout(250);expect((await state(page)).actors.nobita.walkDistance).toBeCloseTo(stopped,5);await page.keyboard.up('s');
 await page.locator('[data-profile-terminal]').click();const before=(await state(page)).actors.nobita.position;await page.locator('.terminal-canvas').press('d');await page.waitForTimeout(150);expect((await state(page)).actors.nobita.position).toEqual(before);
});
test('one 3D cabinet context survives ten opens and supports inspection',async({page})=>{await ready(page);await page.waitForFunction(()=>window.__ultraCabinet?.getState().loaded.length===4);for(let i=0;i<10;i++){await page.locator('[data-profile-ultra]').click();await expect(page.locator('.ultra-dialog')).toBeVisible();await page.locator('[data-ultra-id=ace]').click();expect(await page.evaluate(()=>window.__ultraCabinet.getState().selected)).toBe('ace');await page.locator('[data-ultra-back]').click();await page.locator('[data-ultra-close]').click();}expect(await page.evaluate(()=>window.__ultraCabinet.getState().contexts)).toBe(1);expect(await page.locator('.ultra-dialog').count()).toBe(1);await expect(page.locator('[data-profile-ultra]')).toBeFocused();});
test('Ruru responds and goes to sleep with the music without waking on pause',async({page})=>{await ready(page);await page.locator('[data-profile-ruru]').click();expect((await state(page)).ruru.state).toBe('wave');await page.locator('[data-music-box]').click();await expect.poll(async()=>await page.evaluate(()=>window.__homeMusicDebug.getState().playing)).toBe(true);await page.evaluate(()=>window.__profileAdventureDebug.advanceTime(100));expect((await state(page)).ruru.state).toBe('sleep');await page.locator('[data-music-box]').click();expect((await state(page)).ruru.state).toBe('sleep');});
test('all 25 actions have reachable stations and real distinct animation frames',async({page})=>{await ready(page);const report=await page.evaluate(async()=>{const {ProfileRoomSimulation}=await import('/src/profile/ProfileRoomSimulation.ts');const {CABIN_ACTIONS}=await import('/src/profile/cabinActions.ts');const manifest=await fetch('/assets/profile/dungeon-v5/actions/manifest.json').then(r=>r.json());const results=[];for(const [id,actions]of Object.entries(CABIN_ACTIONS))for(const action of actions){const sim=new ProfileRoomSimulation(false);for(const [other,a]of Object.entries(sim.getState().actors))if(other!==id){a.visible=false;a.nextDecisionAt=1e9;}sim.advanceTime(13);sim.triggerActor(id,action.id);let arrived=false;for(let i=0;i<9000;i++){sim.step(1/60);if(sim.getState().actors[id].manualAction===action.id){arrived=true;break;}}results.push({id,action:action.id,arrived,frames:manifest[`${id}/${action.id}`]?.count||0});}return results;});expect(report.filter(x=>!x.arrived)).toEqual([]);expect(report).toHaveLength(25);expect(report.every(x=>x.frames>=8)).toBe(true);});

test('mobile joystick moves the selected actor without scrolling and releases cleanly',async({page})=>{
 await page.setViewportSize({width:390,height:844});await ready(page);await page.evaluate(()=>window.__profileAdventureDebug.reset());await page.locator('[data-profile-actor=nobita]').click();await page.locator('.cabin-stick').scrollIntoViewIfNeeded();const stick=await page.locator('.cabin-stick').boundingBox(),before=await state(page),scroll=await page.evaluate(()=>scrollY);
 await page.mouse.move(stick.x+stick.width/2,stick.y+stick.height/2);await page.mouse.down();await page.mouse.move(stick.x+stick.width*.79,stick.y+stick.height*.5);await page.waitForTimeout(600);await page.mouse.up();expect((await state(page)).actors.nobita.walkDistance).toBeGreaterThan(before.actors.nobita.walkDistance);expect(await page.evaluate(()=>scrollY)).toBe(scroll);await page.waitForTimeout(100);const stop=(await state(page)).actors.nobita.walkDistance;await page.waitForTimeout(200);expect((await state(page)).actors.nobita.walkDistance).toBeCloseTo(stop,5);
});
test('diagonal movement is normalized and sprite failure retains a usable room',async({page})=>{
 await page.route('**/dungeon-v5/sprites/nobita-down-idle.webp',r=>r.abort());await ready(page);const distances=await page.evaluate(async()=>{const {ProfileRoomSimulation:S}=await import('/src/profile/ProfileRoomSimulation.ts');return [[1,0],[1,1]].map(([x,y])=>{const s=new S(true);for(const [id,a]of Object.entries(s.getState().actors))if(id!=='nobita')a.visible=false;s.control('nobita');s.setInput(x,y);s.advanceTime(1);return s.getState().actors.nobita.walkDistance;});});expect(distances[0]).toBeCloseTo(distances[1],5);await page.locator('[data-profile-actor=nobita]').click();expect((await state(page)).controlledActor).toBe('nobita');await expect(page.locator('[data-profile-terminal]')).toBeEnabled();
});
