import type { ProfileActorId } from './profileAdventureAssets';
import type { ProfileRoomStationId } from './profileRoomLayout';
export type CabinAction = {id:string;label:string;station:ProfileRoomStationId;facing:'up'|'down'|'left'|'right';duration:number;event?:'drawer'|'string'|'concert'};
export const CABIN_ACTIONS:Record<ProfileActorId,CabinAction[]> = {
 nobita:[{id:'cat-cradle',label:'翻花绳',station:'performance',facing:'down',duration:9,event:'string'},{id:'computer',label:'用电脑',station:'primary-desk',facing:'up',duration:14},{id:'manga',label:'看漫画',station:'sofa-left',facing:'down',duration:16},{id:'nap',label:'打瞌睡',station:'sofa-right',facing:'down',duration:22},{id:'paper-plane',label:'折纸飞机',station:'secondary-desk',facing:'down',duration:10}],
 doraemon:[{id:'dorayaki',label:'吃铜锣烧',station:'sofa-right',facing:'down',duration:12},{id:'pocket',label:'翻四次元口袋',station:'primary-desk',facing:'down',duration:9,event:'drawer'},{id:'copter',label:'检查竹蜻蜓',station:'model-bench',facing:'down',duration:10},{id:'bell',label:'擦铃铛',station:'performance',facing:'down',duration:8},{id:'belly',label:'开心拍肚子',station:'secondary-desk',facing:'down',duration:8}],
 shizuka:[{id:'violin',label:'拉小提琴',station:'performance',facing:'down',duration:16},{id:'tea',label:'喝茶',station:'secondary-desk',facing:'down',duration:10},{id:'book',label:'看书',station:'sofa-left',facing:'down',duration:16},{id:'flowers',label:'浇花',station:'flowers',facing:'left',duration:10},{id:'pet-ruru',label:'摸摸噜噜',station:'ruru',facing:'left',duration:10}],
 gian:[{id:'sing',label:'唱歌',station:'performance',facing:'down',duration:10,event:'concert'},{id:'rhythm',label:'打节拍',station:'tv-console',facing:'down',duration:8},{id:'weights',label:'举小哑铃',station:'model-bench',facing:'down',duration:12},{id:'snacks',label:'分享点心',station:'secondary-desk',facing:'down',duration:10},{id:'laugh',label:'叉腰大笑',station:'sofa-right',facing:'down',duration:8}],
 suneo:[{id:'figure',label:'把玩手办',station:'model-bench',facing:'down',duration:14},{id:'polish',label:'擦展柜',station:'ultra-cabinet',facing:'up',duration:10},{id:'photo',label:'拍收藏照片',station:'ultra-cabinet',facing:'up',duration:10},{id:'handheld',label:'玩掌机',station:'tv-console',facing:'down',duration:16},{id:'hair',label:'整理头发',station:'sofa-left',facing:'down',duration:8}]
};
